"use client";
import { useActionState, useState } from "react";
import { saveRenewalFollowup } from "./followup-actions";
import { useLanguage } from "@/context/LanguageContext";
export type Followup = {student_id:string;status:string;last_contact:string|null;next_followup:string|null;note:string;updated_at:string};
export default function FollowupForm({studentId,record}:{studentId:string;record?:Followup}) {
 const {language}=useLanguage(); const sk=language==="sk";
 const [state,action,pending]=useActionState(async(previous:{error?:string;success?:string},form:FormData)=>{try{return await saveRenewalFollowup(previous,form);}catch{return {error:sk?"Uloženie zlyhalo. Skúste znova.":"Save failed. Please try again."};}},{});
 const [status,setStatus]=useState(record?.status||"to_contact"),[note,setNote]=useState(record?.note||""),[last,setLast]=useState(record?.last_contact||""),[next,setNext]=useState(record?.next_followup||"");
 const statuses=[["to_contact",sk?"Ozvať sa":"Contact"],["contacted",sk?"Kontaktovaný":"Contacted"],["waiting",sk?"Čaká sa na odpoveď":"Waiting for reply"],["later",sk?"Ozvať sa neskôr":"Contact later"],["closed",sk?"Uzavreté":"Closed"]];
 return <details className="mt-3 w-full"><summary className="cursor-pointer font-semibold text-[#2F3AA2]">{sk?"Záznam kontaktovania":"Follow-up record"}{record?.next_followup ? ` · ${sk?"ďalší kontakt":"next contact"} ${record.next_followup.split("-").reverse().join(".")}` : ""}</summary><form action={action} aria-busy={pending} className="mt-3 space-y-3"><input type="hidden" name="student_id" value={studentId}/><input type="hidden" name="version" value={record?.updated_at||""}/><fieldset disabled={pending||!!state.success} className="grid gap-3 sm:grid-cols-2"><label className="text-sm">{sk?"Stav":"Status"}<select name="status" value={status} onChange={e=>setStatus(e.target.value)} className="mt-1 block w-full rounded-lg border p-2">{statuses.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm">{sk?"Posledný kontakt":"Last contact"}<input type="date" name="last_contact" value={last} onChange={e=>setLast(e.target.value)} className="mt-1 block w-full rounded-lg border p-2"/></label><label className="text-sm">{sk?"Ďalšie kontaktovanie":"Next follow-up"}<input type="date" name="next_followup" value={next} onChange={e=>setNext(e.target.value)} className="mt-1 block w-full rounded-lg border p-2"/></label><label className="text-sm sm:col-span-2">{sk?"Interná poznámka":"Internal note"}<textarea name="note" maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} className="mt-1 block w-full rounded-lg border p-2" rows={3}/></label><button className="rounded-lg bg-[#2F3AA2] px-4 py-2 font-semibold text-white">{pending?(sk?"Ukladám…":"Saving…"):(sk?"Uložiť záznam":"Save record")}</button></fieldset>{state.error&&<p role="alert" className="text-sm text-red-700">{state.error}</p>}{state.success&&<p role="status" className="text-sm text-[#2F3AA2]">{state.success} {sk?"Obnovte stránku pred ďalšou úpravou.":"Refresh the page before another edit."}</p>}</form></details>;
}
