"use client";
import { useActionState, useState } from "react";
import { saveRenewalFollowup } from "./followup-actions";
export type Followup = {student_id:string;status:string;last_contact:string|null;next_followup:string|null;note:string;updated_at:string};
export default function FollowupForm({studentId,record}:{studentId:string;record?:Followup}) {
 const [state,action,pending]=useActionState(async(previous:{error?:string;success?:string},form:FormData)=>{try{return await saveRenewalFollowup(previous,form);}catch{return {error:"Uloženie zlyhalo. Skúste znova."};}},{});
 const [status,setStatus]=useState(record?.status||"to_contact"),[note,setNote]=useState(record?.note||""),[last,setLast]=useState(record?.last_contact||""),[next,setNext]=useState(record?.next_followup||"");
 return <details className="mt-3 w-full"><summary className="cursor-pointer font-semibold text-[#2F3AA2]">Záznam kontaktovania{record?.next_followup ? ` · ďalší kontakt ${record.next_followup.split("-").reverse().join(".")}` : ""}</summary><form action={action} aria-busy={pending} className="mt-3 space-y-3"><input type="hidden" name="student_id" value={studentId}/><input type="hidden" name="version" value={record?.updated_at||""}/><fieldset disabled={pending||!!state.success} className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Stav<select name="status" value={status} onChange={e=>setStatus(e.target.value)} className="mt-1 block w-full rounded-lg border p-2">{[['to_contact','Ozvať sa'],['contacted','Kontaktovaný'],['waiting','Čaká sa na odpoveď'],['later','Ozvať sa neskôr'],['closed','Uzavreté']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm">Posledný kontakt<input type="date" name="last_contact" value={last} onChange={e=>setLast(e.target.value)} className="mt-1 block w-full rounded-lg border p-2"/></label><label className="text-sm">Ďalšie kontaktovanie<input type="date" name="next_followup" value={next} onChange={e=>setNext(e.target.value)} className="mt-1 block w-full rounded-lg border p-2"/></label><label className="text-sm sm:col-span-2">Interná poznámka<textarea name="note" maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} className="mt-1 block w-full rounded-lg border p-2" rows={3}/></label><button className="rounded-lg bg-[#2F3AA2] px-4 py-2 font-semibold text-white">{pending?"Ukladám…":"Uložiť záznam"}</button></fieldset>{state.error&&<p role="alert" className="text-sm text-red-700">{state.error}</p>}{state.success&&<p role="status" className="text-sm text-[#2F3AA2]">{state.success} Obnovte stránku pred ďalšou úpravou.</p>}</form></details>;
}
