import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
const student='00000000-0000-4000-8000-000000000001', other='00000000-0000-4000-8000-000000000002', teacher='00000000-0000-4000-8000-000000000003', outsider='00000000-0000-4000-8000-000000000004', admin='00000000-0000-4000-8000-000000000005', lesson='00000000-0000-4000-8000-000000000006';
await db.exec(`create role anon; create role authenticated; create schema auth;
create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create table auth.users(id uuid primary key,email_confirmed_at timestamptz);
create table profiles(id uuid primary key,role text,status text);
create table lessons(id uuid primary key,student_id uuid,teacher_id uuid);
create table lesson_reports(id uuid primary key,lesson_id uuid,student_id uuid,teacher_id uuid,topic text,progress text,student_note text,homework text,next_focus text,private_teacher_note text,updated_at timestamptz);
grant usage on schema auth to authenticated,anon; grant select on profiles,lessons,lesson_reports to authenticated,anon;
grant update on lesson_reports to authenticated;
insert into profiles values('${student}','student','active'),('${other}','student','active'),('${teacher}','teacher','active'),('${outsider}','teacher','active'),('${admin}','admin','active');
insert into auth.users values('${student}',now()),('${other}',now()),('${teacher}',now()),('${outsider}',now()),('${admin}',now());
insert into lessons values('${lesson}','${student}','${teacher}');
insert into lesson_reports values('${lesson}','${lesson}','${student}','${teacher}','Practice','normal_progress','Shared feedback','Shared homework','Conversation','Staff secret',now());
alter table lessons enable row level security;
create policy lesson_read on lessons for select using(true);
alter table lesson_reports enable row level security;
-- Deliberately broad legacy policies must not leak private fields.
create policy legacy_read on lesson_reports for select using(true);
create policy teacher_update on lesson_reports for update to authenticated using(teacher_id=auth.uid()) with check(teacher_id=auth.uid());`);
const migration=readFileSync(new URL('../supabase/migrations/202610030008_report_privacy.sql',import.meta.url),'utf8');
await db.exec(migration); await db.exec(migration);
await db.exec(readFileSync(new URL('../supabase/migrations/202610030009_portal_session_guards.sql',import.meta.url),'utf8'));
async function login(id){await db.exec(`reset role; set request.jwt.claim.sub='${id}'; set role authenticated;`);}
await login(student);
assert.equal((await db.query('select * from lesson_reports')).rows.length,0,'direct student read cannot expose private fields');
const shared=(await db.query('select * from student_lesson_reports()')).rows;
assert.equal(shared.length,1); assert.equal(shared[0].homework,'Shared homework');
assert.ok(!('private_teacher_note' in shared[0])); assert.ok(!('teacher_id' in shared[0]));
await assert.rejects(db.query('select private_teacher_note from student_lesson_reports()'),/does not exist/);
await login(other);assert.equal((await db.query('select * from student_lesson_reports()')).rows.length,0);
await login(teacher);assert.equal((await db.query('select private_teacher_note from lesson_reports')).rows[0].private_teacher_note,'Staff secret');
assert.equal((await db.query('select * from student_lesson_reports()')).rows.length,0);
await db.exec("update lesson_reports set private_teacher_note='Updated staff secret'");
await login(outsider);assert.equal((await db.query('select * from lesson_reports')).rows.length,0);
await login(admin);assert.equal((await db.query('select * from lesson_reports')).rows.length,1);
await db.exec(`reset role;update profiles set status='inactive' where id='${teacher}'`);
await login(teacher);assert.equal((await db.query('select * from lesson_reports')).rows.length,0);
await db.exec(`reset role;update auth.users set email_confirmed_at=null where id='${student}'`);
await login(student);assert.equal((await db.query('select * from student_lesson_reports()')).rows.length,0);
await db.exec(`reset role;update auth.users set email_confirmed_at=now() where id='${student}';update profiles set status='inactive' where id='${student}'`);
await login(student);assert.equal((await db.query('select * from student_lesson_reports()')).rows.length,0);
await db.exec('reset role;set role anon');assert.equal((await db.query('select * from lesson_reports')).rows.length,0);
await assert.rejects(db.query('select * from student_lesson_reports()'),/permission denied/);
await db.close();console.log('PASS: private report fields hidden from students and anonymous users, own shared reports, verified active accounts, assigned staff access and migration reruns');
