"use client";
import {useActionState,useState} from "react";
import {savePreferences} from "./actions";
export type Preferences={teacher_id:string;accepting_students:boolean;languages:string[];levels:string[];days:string[];time_from:string|null;time_to:string|null;max_new_students:number;note:string;updated_at:string};
export default function PreferencesForm({record}:{record:Preferences|null}) {
 const [state,action,pending]=useActionState(async(previous:{error?:string;success?:string},form:FormData)=>{try{return await savePreferences(previous,form);}catch{return {error:"Uloženie zlyhalo. Vaše údaje zostali vyplnené."};}},{});
 const [accepting,setAccepting]=useState(record?.accepting_students||false),[languages,setLanguages]=useState(record?.languages||[]),[levels,setLevels]=useState(record?.levels||[]),[days,setDays]=useState(record?.days||[]),[from,setFrom]=useState(record?.time_from?.slice(0,5)||""),[to,setTo]=useState(record?.time_to?.slice(0,5)||""),[capacity,setCapacity]=useState(String(record?.max_new_students||0)),[note,setNote]=useState(record?.note||"");
 const choices=(name:string,options:string[][],selected:string[],set:(values:string[])=>void)=><div className="flex flex-wrap gap-3">{options.map(([value,label])=><label key={value} className="rounded-xl border p-3 text-sm"><input type="checkbox" name={name} value={value} checked={selected.includes(value)} onChange={e=>set(e.target.checked?[...selected,value]:selected.filter(item=>item!==value))} className="mr-2 accent-[#2F3AA2]"/>{label}</label>)}</div>;
 return <form action={action} aria-busy={pending} className="mt-6"><input type="hidden" name="version" value={record?.updated_at||""}/><fieldset disabled={pending||!!state.success} className="space-y-5"><label className="block font-semibold"><input type="checkbox" name="accepting" value="true" checked={accepting} onChange={e=>setAccepting(e.target.checked)} className="mr-2"/>Prijímam nových študentov</label><div><p className="mb-2 font-semibold">Jazyky</p>{choices('languages',[['English','Angličtina'],['German','Nemčina'],['Spanish','Španielčina'],['Italian','Taliančina'],['French','Francúzština'],['Portuguese','Portugalčina'],['Hungarian','Maďarčina'],['Polish','Poľština'],['Russian','Ruština'],['Chinese','Čínština'],['Slovak','Slovenčina'],['Ukrainian','Ukrajinčina'],['Modern Hebrew','Moderná hebrejčina']],languages,setLanguages)}</div><div><p className="mb-2 font-semibold">Úrovne</p>{choices('levels',['A1','A2','B1','B2','C1','C2'].map(value=>[value,value]),levels,setLevels)}</div><div><p className="mb-2 font-semibold">Preferované dni (voliteľné)</p>{choices('days',[['1','Pondelok'],['2','Utorok'],['3','Streda'],['4','Štvrtok'],['5','Piatok'],['6','Sobota'],['7','Nedeľa']],days,setDays)}</div><div className="grid gap-4 sm:grid-cols-3"><label>Čas od<input type="time" name="from" value={from} onChange={e=>setFrom(e.target.value)} className="mt-1 block w-full rounded-lg border p-3"/></label><label>Čas do<input type="time" name="to" value={to} onChange={e=>setTo(e.target.value)} className="mt-1 block w-full rounded-lg border p-3"/></label><label>Kapacita nových študentov<input required type="number" min={0} max={20} name="capacity" value={capacity} onChange={e=>setCapacity(e.target.value)} className="mt-1 block w-full rounded-lg border p-3"/></label></div><label className="block">Poznámka pre správcu<textarea name="note" maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} rows={3} className="mt-1 block w-full rounded-lg border p-3"/></label><button className="rounded-xl bg-[#2F3AA2] px-5 py-3 font-semibold text-white">{pending?'Ukladám…':'Uložiť preferencie'}</button></fieldset>{state.error&&<p role="alert" className="mt-4 text-red-700">{state.error}</p>}{state.success&&<p role="status" className="mt-4 text-[#2F3AA2]">{state.success} Obnovte stránku pred ďalšou úpravou.</p>}</form>;
}
