import Link from "next/link";
import {requireRole} from "@/lib/auth";
import {createSupabaseServerClient} from "@/lib/supabase/server";
import AdminCreateLessonForm from "../lessons/AdminCreateLessonForm";
import {formatLanguage} from "@/lib/portalLabels";
export default async function MatchingPage(){
 await requireRole("admin");const db=await createSupabaseServerClient();
 const [people,prefs,packages]=await Promise.all([db.from("profiles").select("id,full_name,email,role").eq("status","active").in("role",['teacher','student']),db.from("teacher_preferences").select("*"),db.from("lesson_packages").select("id,student_id,total_lessons,remaining_lessons").eq("status","active").gt("remaining_lessons",0)]);
 const teachers=(people.data??[]).filter(p=>p.role==='teacher');const students=(people.data??[]).filter(p=>p.role==='student');
 const open=teachers.filter(teacher=>prefs.data?.some(row=>row.teacher_id===teacher.id&&row.accepting_students));
 const days=['Pondelok','Utorok','Streda','Štvrtok','Piatok','Sobota','Nedeľa'];
 const unavailable=people.error||prefs.error||packages.error;
 return <main className="mx-auto max-w-6xl px-5 py-10"><h1 className="text-3xl font-semibold">Priradenie študenta k lektorovi</h1><p className="mt-4 text-gray-600">Preferencie lektora sú podklad pre vaše rozhodnutie, nie automatická rezervácia. Dohodnite jazyk, úroveň a termín. Priradenie potvrdíte vytvorením prvej hodiny; tým lektor získa prístup k potrebným študijným údajom bez kontaktného e-mailu.</p>{unavailable?<p role="alert" className="mt-6 text-red-700">Údaje nie sú dostupné. Overte migrácie alebo obnovte stránku. Priradenie je zatiaľ zablokované.</p>:<><section className="mt-6 space-y-4">{teachers.map(teacher=>{const preference=prefs.data?.find(row=>row.teacher_id===teacher.id);return <article key={teacher.id} className="rounded-2xl border border-indigo-100 bg-white p-5"><h2 className="text-xl font-semibold">{teacher.full_name||teacher.email}</h2><p className="mt-2 font-semibold text-[#2F3AA2]">{preference?.accepting_students?'Prijíma nových študentov':'Nových študentov neprijíma / preferencie nezadané'}</p>{preference&&<><p className="mt-2">Jazyky: {preference.languages.map(formatLanguage).join(', ')||'—'} · Úrovne: {preference.levels.join(', ')||'—'}</p><p className="mt-2">Dni: {preference.days.map((day:string)=>days[Number(day)-1]).join(', ')||'Po dohode'} · Čas Bratislava: {preference.time_from?.slice(0,5)||'—'} – {preference.time_to?.slice(0,5)||'—'}</p><p className="mt-2">Kapacita nových študentov: {preference.max_new_students} (údaj lektora, nie automatický počet voľných miest)</p><p className="mt-2 whitespace-pre-wrap text-gray-600">{preference.note}</p></>}</article>;})}</section>{open.length?<AdminCreateLessonForm students={students} teachers={open} packages={packages.data??[]}/>:<p className="mt-6 text-gray-600">Žiadny aktívny lektor zatiaľ neuviedol, že prijíma nových študentov.</p>}</>}<Link href="/admin/dashboard" className="mt-6 inline-block font-semibold text-[#2F3AA2] underline">Späť na prehľad</Link></main>;
}
